- pom.xml
- src/main/mule/salesforce-data-api.xml
…tudent DB to Contact endpoints
> Contact endpoint includes External ID

- pom.xml
- src/main/mule/salesforce-data-api.xml
Added support for other session topics and updated API specification version.
> Updated API version

- pom.xml
- src/main/mule/salesforce-data-api.xml
Had create a new version for the API specification as Anypoint Studio wouldn't detect the new changes
> Updated API for session types

- pom.xml
- src/main/mule/salesforce-data-api.xml
Added support for "Game Day" and "Soccer and Writing" session topics on all session endpoints
> added support for session topics

- src/main/mule/salesforce-data-api.xml
Added the Grade and Birthdate fields to the /search endpoint and cleaned the payload mapping for the response message
> added required fields for student search results

- pom.xml
- src/main/mule/salesforce-data-api.xml
fixed single date query and added support for Contact Type SCORES Student on POST contacts endpoint
> fixed single date query

- pom.xml
- src/main/mule/salesforce-data-api.xml
adding post api to create assessments
> assessments post api

- src/main/mule/coach.xml
added use heacount support for coach/coachid/all/ and coach/coahid/teamseasons endpoints
> added use heacount support

- pom.xml
- src/main/mule/coach.xml
- src/main/mule/contacts.xml
set default values for contact type and record type id, updated multiple modules
> added default values

- src/main/mule/contacts.xml
- src/main/resources/application-types.xml
Added School Attending and AccountId fields to contacts patch endpoint
> Added School Site fields

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- src/main/mule/waiver.xml
hoping this change is sufficient to support this additional field on the Reg form(s)
> added PaperReceived to Waiver io

- src/main/mule/coach.xml
**Changes:**
- Added `Contact__r.Incomplete_Record__c field` to the SOQL query.
- Added `StudentIncompleteRecord` with default value `true` and type conversion.
**Files Modified:**
- `src/main/mule/coach.xml`
**Test example:**
> Feature/154 is complete field (Add "StudentIncompleteRecord")

- docs/Scores - Salesforce Data API.postman_collection.json
Add missing endpoint: /coach/{coachId}/teamseasons/{teamSeasonId}/sessions/{sessionId}/assessments
> /assessments endpoint

- pom.xml
- src/main/mule/global.xml
- New endpoint GET `/seasons/{seasonId}/teamSeasons` for [ticket #220](https://github.com/AmericaSCORESBayArea/salesforce-data-api/issues/220)
- Added 'endDate' and 'isWithinDateRange' to GET `teamSeasons/`
- Disabled the 'Birthday' field as a requirement in `types.Contact` in `datatypes.raml`.    
There were some issues with publishing 4.0.1. Updated to 4.0.2. No RAML changes included.
> Update to RAML 4.0.2

- mule-artifact.json
- pom.xml
- src/main/resources/api/salesforce-data-api.raml
Description:
Updated the `/searchByPhoneNumber` endpoint's query parameter `phoneNumber` to check for the pattern `'^\+?[1-9]\d{1,14}$'` which is E.164 international phone number format. 
If it is not in the pattern, The API responds with the status `400 Bad Request` as shown below in the screenshots of tests. 
```
/searchByPhoneNumber:
get:
displayName: Get matching contacts for a given phone number
description: Get contacts matching a search string with a phone number (to be used for Student contacts for now)
queryParameters:
phoneNumber:
displayName: phoneNumber
description: Phone number
type: string
required: true
pattern: '^\+?[1-9]\d{1,14}$'  # E.164 international phone number format
responses:
200:
body:
application/json:
type: types.Contact[]
400:
body:
application/json:
example: …
```
> Fix/210 Handle Wrong Phone Number Input

- mule-artifact.json
- pom.xml
**Description:**
Updating all dependencies:
- Mule Runtime: **4.4.0 -> 4.6.3**
- Java: **v11 -> v17**
- HTTP Connector: **1.7.3 -> 1.9.3**
- Sockets Connector: **1.2.3 -> 1.2.4**
- APIKIT Module: **1.9.1 -> 1.10.4**
- Salesforce Connector: **10.18.3 -> 10.20.3**
The deployment was successfully tested on [a seperate runtime](https://anypoint.mulesoft.com/cloudhub/#/console/applications/cloudhub/salesforce-data-api-test-with-proxy/dashboard?domain=salesforce-data-api-test-with-proxy).
> Update all dependencies, including Mule Runtime & Java 

- src/main/mule/enrollments.xml
Fixed the Issue `DEL /enrollments - 'Enrollment/s Not Found' is missing` with implementing a choice in the .xml flow as follows:
1. Success flow: If post delete payload's `successful` flag is true, then return status code as `200 OK` 
2. Error flow: If post delete payload's size with filter(no. of items with `item.successful` is `false`) and without filter are same, then return status code as `404 Not Found`
3. Partial Success flow: Else Case of above, then return status code as `206 Partial Content`
`DELETE` `{{base_url}}/enrollments`
```
[
{
"EnrollmentId": "a0mU8000000hMzlIAE"
}
]
```
```
[
{
"EnrollmentId": "a0mU8000000hMy9IAE"
}
]
```
```
[
{
"EnrollmentId": "a0mU8000000hN1NIAU"
},
{
"EnrollmentId": "a0mU8000000hMzlIAE"
}
]
```
> Fix/208 Delete Enrollment/s Not Found

- .github/workflows/production-on-push-build-and-deploy.yml
- scripts/disable-validations.sh
- scripts/version.sh
**Description:**
This PR includes 3 new files:
- `production-on-push-build-and-deploy.yml` - Deployment of the Mule app to the Production environment. Unlike the Sandbox, the production has disabled validation of requests and a step to publish a new release of the app.
- `version.sh` - A script to determine the version for the new release.
- `disable-validation.sh`
**How the script `version.sh` works:**
The script looks at the previous commit message and fetches a keyword from it to determine the version increment:
- **Major**: Indicates a breaking change. (e.g., 1.0.0 -> 2.0.0)
```bash
git commit -m "Breaking change to API (major)"
```
- **Minor**: Indicates a new feature or enhancement. (e.g., 1.0.0 -> 1.1.0)
```bash
git commit -m "Add new feature to API (minor)"
```
- **Patch**: …
> CI/CD Deployment: Production

- docs/Scores - Student Registration Steps.postman_collection.json
- src/main/mule/coach.xml
- src/main/mule/contacts.xml
- src/main/resources/api/datatypes.raml
- src/main/resources/api/enrollment-examples.raml
- src/main/resources/api/salesforce-data-api.raml
- src/main/resources/api/teamseason-full-examples.raml
1) PATCH Contact: disable `Student_Record_Complete__c` edit functionality (delete: `(Student_Record_Complete__c: vars.CompleteRecord) if(vars.CompleteRecord?) `)
2) PATCH Contact/finishRegistration: delete "CompleteRecord" variable
3) Update `Incomplete_Record__c` to`Student_Record_Complete__c` in SOQL requests
4) Update `StudentIncompleteRecord` and `IncompleteRecord` to `StudentRecordComplete` in payload returned to the client 
5) Update all related documentation
> Fix: `Incomplete_Record__c` -> `Student_Record_Complete__c`

- src/main/mule/contacts.xml
- src/main/resources/api/datatypes.raml
Key Updates:
- **LatestWaiverDate** - The field is updated through Salesforce database and simple retrieved.
- **LatestEnrolledSiteId**: Updated based on Enrollment.Site (AccountID) from the enrollment record retrieved through another API flow.
- **LatestEnrolledEndDate**: Updated based on Enrollment.End_date from the enrollment record retrieved another API flow.
- **LatestEnrolledSiteName**: Populated using Account.name retrieved through another API flow.
> New fields to the `contact` object: LatestWaiverDate, LatestEnrolledEndDate, LatestEnrolledSiteId, LatestEnrolledSiteName

- docs/Scores - Salesforce Data API.postman_collection.json
- src/main/mule/tasks.xml
- src/main/resources/api/datatypes.raml
- src/main/resources/api/salesforce-data-api.raml
This PR introduces 4 methods for tasks and tags methods:
1) GET `/tasks?contactId={{contactId}}` - to retrieve tasks based on the contactId
2) POST `/tasks` - to create a new task
3) PATCH `/tasks/{{taskId}}` - to modify an existing task based on its id
4) GET `/tasks/{{taskId}}/tags` - to retrieve tags associated with a particular task (no examples at the moment)
---
Please note that the following fields have the following properties:
`Priority` :
- Double between "0" and "100"
- Used to calculate Priority_Icon__c:  `IF( Priority__c <= 40, "🟢", IF( Priority__c <= 80, "🟡", "🔴" ) )`
`Task Status`, limited to:
- Unstarted
- Started
- Complete
`Task Types`, limited to: 
- Take Attendance
- Update Registration
- Compile Report
- Record PACER Scores
- Record End-of-Session Video
- Make a …
> Tasks and Tags: some starter methods 

- docs/Scores - Salesforce Data API.postman_collection.json
- src/main/mule/teamseasons.xml
- src/main/resources/api/salesforce-data-api.raml
**Endpoint**: Adds the `GET /teamSeasons/searchByTeamName` endpoint.
**Functionality**: Retrieves 8 `TeamSeasonId` based on the `teamName` query parameter.
**Examples:**
> TeamSeasons: Retrieve `TeamSeasonId` based on `TeamName`

- .github/workflows/postman_autoupdate.yml
- docs/Scores - Salesforce Data API.postman_collection.json
- docs/concurrency_test.py
- src/main/mule/contacts.xml
- src/main/mule/sessions.xml
- src/main/mule/teamseasons.xml
- src/main/resources/api/datatypes.raml
This PR combines multiple updates for improved API functionality and documentation:  
- **Endpoint**: `GET /contacts/search?searchString=Aleks`  
- **Update**:  
- Switched from **SOSL** to **SOQL** for precise filtering of the `Name` field.  
- Used `%` wildcards on both sides of the search string for flexible matching.  
- **Reason**: SOSL lacked scope control, leading to unwanted results.  
- [More on SOQL vs SOSL](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_sosl_intro.htm).  
- **Endpoints**:  
- `GET /tasks`:  
- Added an optional `sessionId` parameter to filter tasks for a specific session.  
- `DELETE /tasks/{taskId}`:  
- Introduced a validation check to ensure the task exists before deletion, preventing accidental removal of …
> Sandbox: SOSL to SOQL and other updates | Jan 15

- src/main/mule/main-api.xml
- Rename `Origin` to `Source of Request`
- Add `X-Platform` and `X-Build-Version` to `Source of Request`
> Enhance error logging with device information (`X-Platform` and `X-Build-Version`)

- docs/Scores - Salesforce Data API.postman_collection.json
- src/main/mule/tasks.xml
- src/main/resources/api/salesforce-data-api.raml
> Add endpoint GET `/tasks/statuses`

- src/main/mule/sessions.xml
> DELETE `/sessions`: add deletion of tasks

- docs/Scores - Salesforce Data API.postman_collection.json
- src/main/mule/sessions.xml
> Update `POST /sessions` to create tasks 

- src/main/mule/sessions.xml
Name: "Take attendance {sessionDate}" -> "Take attendance"
TaskType: "" -> "To Do"
> Update Payload for Task Creation When A session is Created
