AmericaSCORESBayArea/salesforce-data-api

pom.xml

MUnit plugin version 2.3.5 was causing a missing dependency error. Downgraded to 2.2.5

downgrade munit plugin/update maven plugin

---

pom.xml
src/main/mule/salesforce-data-api.xml

added ranges choice to get/coach/coachid/all endpoint.
If only "firstDate" value is sent, endpoint retrieves sessions for the selected date.
If "firstDate" and "secondDate" parameters are entered, the endpoint retrieves all sessions within the date range input.

added range choice to /all endpoint

---

src/main/mule/salesforce-data-api.xml

Modified get:coach/coachid/teamseasons endpoint so that by sending today's date (or a date that is is inside an older or future season), the api returns only teamseasons for the corresponding season.

teamseason filter by current season

---

src/main/mule/contacts.xml

**Description**:
This pull request adds validation to the `get/contacts` endpoint to ensure parameters are present. It throws a 400 error when either (`externalStudentId` and `externalStudentIdSource`) or both (`firstName` and `lastName`) are missing. Prior to this change, it would return 200 with an empty array.
**Example of 200 response:**
**Example of 400 response:**

#195 `GET /contacts` Handle Missing Parameters (Throw 400 Error)

---

src/main/mule/global.xml
src/main/mule/main-api.xml

**Description:**
Enabled validation based on the RAML file and included a detailed error description in "details" field for 400 error responses. Now, the server will return "Bad Request" if payload / parameters are missing. No extra error handling per flow is required anymore. 
Here is an example:

Enable validation + add "details" field to 400 error response

---

pom.xml
src/main/mule/global.xml

Updated RAML version from [3.0.54](https://anypoint.mulesoft.com/exchange/portals/americascores-bayarea/6c091e72-50d1-49ac-b04d-ee5bb9bc9dbd/salesforce-data-api/minor/3.0/) to the latest [4.0.0](https://anypoint.mulesoft.com/exchange/portals/americascores-bayarea/6c091e72-50d1-49ac-b04d-ee5bb9bc9dbd/salesforce-data-api/minor/4.0/).

Migrate to RAML 4.0.0

---

docs/Scores - Salesforce Data API.postman_collection.json
src/main/mule/contacts.xml
src/main/resources/api/datatypes.raml

**Description**:
Update the endpoint to POST new contacts making a `Birthday` field optional.
**RAML Link**:
Will be included in RAML 4.0.1 #222 
**RAML Specification**:
```raml
/contacts: 
post:
displayName: Register Student
description: Creates a new student (Contact->recordType=SCORES Student) in the America SCORES Salesforce database
body:
application/json:
description: payload should be new Contact with values filled out from registration form
type: types.Contact
responses:
200:
description: Successful Registration
body:
application/json:
example:
ContactId: abc123
400:
body:
application/json:
example:
message: Error in registration
```
<details>
<summary>types.Contact</summary>
``` raml
Contact:
type: object
description: Salesforce Contact Object
properties:
Id:
type: …
```

POST /contact: Make Birthday field optional

---

.github/workflows/on-push-build-and-deploy.yml
pom.xml
src/main/resources/properties/production.properties
src/main/resources/properties/sandbox.properties

**Description:**
- sfdc.tkn=
- sfdc.password=
- typeform.clientid=
- typeform.clientsecret=
- typeform.tkn=

Sandbox CI/CD: auto-deployment fix

---

pom.xml
src/main/mule/contacts.xml
src/main/mule/global.xml
src/main/resources/api/salesforce-data-api.raml

**Description**:
Update `GET /contacts/search` to include `region`-based filter.
**Specification**:
*Endpoint*: `GET /contacts/search`
*Query Parameters*:
Name: searchString
Type: string
Required: true
Name: region
Type: string
Required: false
**Test example**:
`{{base_url}}/contacts/search?searchString=Angel`
`{{base_url}}/contacts/search?searchString=Angel&region=San Francisco Crocker`
`{{base_url}}/contacts/search?searchString=Angel&region=Hayward`
**Screenshots**:

Include "Region" filter to contacts search

---

src/main/mule/global.xml
src/main/mule/tls-context.xml

Enable HTTPS support by introducing [TLS-context](https://docs.mulesoft.com/http-connector/0.3.9/tls-configuration). CI/CD needs to be modified to generate `keystore.jks` with `keystore.key.password` and `keystore.password` properties.

NEW PROXY: Add HTTPS support

---

src/main/mule/enrollments.xml

Fixed the Issue `GET /enrollments/{enrollmentId}` with implementing a choice in the .xml flow as follows:
1. Success flow: If post get payload is `not null` and size of payload is not equal to Zero, then return the payload and set the status code as `200 OK` 
2. Error flow: otherwise, then set the payload message as `Enrollment Not Found` and status code as `404 Not Found` and return.
`GET` `{{base_url}}/enrollments/{enrollmentId}`
```
GET {{base_url}}/enrollments/a0mU8000000hMriIAE
```
```
GET {{base_url}}/enrollments/a0mU8000000hNriIAE
```

Fix/209 GET /enrollments/{enrollmentId}

---

README.md
local-build.sh
src/main/mule/global.xml.anypoint
src/main/resources/properties/production.properties
src/main/resources/properties/sandbox.properties

From now, the app can be run, developed and tested locally without applying any changes to `global.xml`.
Done:
Notes:
1) Pulling secrets from GH is not possible, unless it is done through GitHub Actions
2) Modifying default arguments is still a requirement as we don't want overwrite all of them (Mulesoft might change them with updates)

Local Run Support + Script To Build the App Locally

---

docs/Scores - Salesforce Data API.postman_collection.json
src/main/mule/contacts.xml
src/main/resources/api/salesforce-data-api.raml

1. Add missing `IncompleteRecord` field in the GET `searchByPhoneNumber` flow.
2. Add search based on `Parent_Phone_02__c` and `Parent_Phone_03__c` to `searchByPhoneNumber` flow 
3. Add DELETE Contact flow enabled only on Sandbox
- If 'production' env is detected, throw 405 error:
- If contact not found, return 404 error:
- If contact is found and successfully deleted, return 200

New `DELETE contacts` flow for Sandbox & fixes for `GET searchByPhoneNumber` flow

---

docs/Scores - Salesforce Data API.postman_collection.json
src/main/mule/waiver.xml
src/main/resources/api/datatypes.raml
src/main/resources/api/salesforce-data-api.raml

1) `get` /waiver by region update
- Waivers are filtered by "Archieved__c"
- Removed "PaperReceived" variable (it should not be here)
---
2) `post` /waiver/{waiverId} - Add `Signed_Paper_Form_Received__c`
- - Replaced `Paper_Form_Received__c` with `Signed_Paper_Form_Received__c`
---
3) New endpoint: `get waiverHistory` to retrieve Waiver History based on `contactId`
Example of how to execute: `{{base_url}}/waiverHistory?contactId=003UQ00000GXyAfYAL`

Fixes for Waiver (get, post) and new endpoint for WaiverHistory

---

src/main/mule/waiver.xml

#298 
- **Changes Implemented**:
1. **Fix "ValidFrom" and "ValidTo"**: Ensure that "ValidFrom" and "ValidTo" fields are corrected, as they were previously swapped.
2. **Move Archive Filtering**: Move the filtering based on the Archive status from the server logic to the SOQL query itself.
3. **Add Filtering Condition**: Add a condition `Waiver_Active_End__c >= TODAY` in the SOQL query to filter out waivers that haven't met the required timelines.
4. **Handle Missing Waivers**: If no waiver is found, return a 404 HTTP status code with the message: "No current waiver found".
- **Examples**:
- **Successful Call**:
- **No Waivers Found**:

Waiver filtering update

---

src/main/mule/contacts.xml

Added new fields `Year_of_Reference_for_Grade_Information__c` and `Grades_child_participated__c` to the following API flows:
- `GET /contacts/{contactId}`
- `GET /contacts`
- `GET /contacts/search`
- `GET /contacts/searchByPhoneNumber`
- `POST /contacts`
- `PATCH /contacts/{contactId}`
- **YearOfReferenceForGradeInformation:** String object representing the year of reference for grade information.
- **GradesChildParticipated:** String object using a `;` separator for multiple grade values (e.g., `"5th;6th"`).

`Year_of_Reference_for_Grade_Information__c` and `Grades_child_participated__c`

---

docs/Scores - Salesforce Data API.postman_collection.json
src/main/mule/tasks.xml
src/main/resources/api/salesforce-data-api.raml

**1. GET {{base_url}}/tasks**
The `sessionId` parameter has been added as an optional filter to retrieve tasks associated with a specific session ID.
**2. DELETE {{base_url}}/tasks/{taskId}**
Deletes a task based on its ID. A validation check is performed to ensure the existence of a valid task before deletion, preventing the removal of non-task objects.

Tasks: add `delete`, modify `get`

---

src/main/mule/contacts.xml

This PR updates the `GET contacts/search?searchString=Aleks` endpoint to use SOQL instead of SOSL for performing search operations. This change was implemented to address the lack of scope control in SOSL when picking values from related object names.
For more details on the differences between SOSL and SOQL, refer to Salesforce documentation:
[SOQL vs SOSL Introduction](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_sosl_intro.htm)

Sandbox: SOSL to SOQL

---

src/main/mule/contacts.xml

This PR updates the search logic to replace the condition `Contact_Type__c = 'SCORES Student'` with `RecordTypeId = '01250000000VBbXAAW'. ` This change improves the search logic and by ensuring that we are not missing any contacts.

Production: replace `Contact_Type__c = 'SCORES Student'` with `RecordTypeId = '01250000000VBbXAAW'`

---

src/main/mule/attendances.xml
src/main/mule/coach.xml
src/main/mule/contacts.xml
src/main/mule/enrollments.xml
src/main/mule/main-api.xml
src/main/mule/sessions.xml
src/main/mule/tasks.xml
src/main/mule/teamseasons.xml

This PR addresses recent changes in the global error handler by adding custom error throws for all `CREATE` and `UPDATE` operations across all flows.
Besides, an improved system of error classification is implemented:
1) `DUPLICATES_DETECTED` and `MALFORMED_ID` detected in all custom errors
2) `SALESFORCE:INVALID_INPUT` is classified as `BAD_REQUEST`
In addition to that, `Payload Attached: No payload attached.` message is appended to the Slack message when payload is not provided.

Sandbox: Update Remaining Error Handling Cases

---

docs/Scores - Salesforce Data API.postman_collection.json
src/main/mule/attendances.xml
src/main/mule/coach.xml
src/main/mule/sessions.xml
src/main/mule/tasks.xml
src/main/resources/api/salesforce-data-api.raml

This PR brings a new endpoint `GET /tasks/{taskId}` and adds a flow to automatically create attendance records when the following events occur:
- `POST /tasks` (A task is created with the type `"Take Attendance"`)
- `PATCH /tasks/{taskId}` (An existing task is updated to have the type `"Take Attendance"`)
- `GET /tasks/{taskId}` (A task with the type `"Take Attendance"` is retrieved)
- `POST /sessions?createAttendances=True` (A session is created with the `createAttendances` flag explicitly set to `True`) 
- `GET /coach/{coachId}/teamseasons/{teamSeasonId}/sessions/{sessionId}/attendances` (Attendance records for a session are retrieved, triggering creation first)
Docummentation is accessible [here](https://github.com/AmericaSCORESBayArea/scoreslabs/blob/main/docs/auto-attendance-creation. …

Sandbox: Automated Attendance Creation

---

docs/Scores - Salesforce Data API.postman_collection.json
src/main/mule/coach.xml
src/main/mule/sessions.xml
src/main/mule/tasks.xml

Update the `DELETE /sessions/{sessionId}` endpoint so that it correctly deletes associated attendance records and prevents deletion of unrelated IDs. 
Link to documentation: https://github.com/AmericaSCORESBayArea/scoreslabs/blob/main/docs/session-delete.md
Link to tests: https://github.com/AmericaSCORESBayArea/scoreslabs/blob/main/qa/salesforce-data-api/delete-session.md

Sandbox: `DELETE /sessions/{sessionId}` improvements

---

.github/workflows/on-push-build-and-deploy.yml
.github/workflows/production-on-push-build-and-deploy.yml
mule-artifact.json
src/main/mule/coach.xml
src/main/mule/contacts.xml
src/main/mule/enrollments.xml
src/main/mule/sessions.xml
src/main/mule/tasks.xml
src/main/mule/teamseasons.xml
src/main/resources/api/datatypes.raml
src/main/resources/api/enrollment-examples.raml
src/main/resources/api/salesforce-data-api.raml

**This PR fixes a few typos in error messages, adds "Other_Drop_Reason_If_Selected__c" field as "OtherDropReason" and introduces two new endpoints:**
- **1. `GET /enrollments/dropreasons`**  
Retrieves the picklist values for the `Drop_Reason__c` field from the `Enrollment__c` object and returns them in the following format:
```json
[
"Schedule Conflict",
"Moved Away",
"Lost Interest",
"Health Reasons",
"Disciplinary Action",
"Other"
]
```
- **2. `GET /tasks/{coachId}/stats`**  
Retrieves basic stats for a coach based on the `Assigned_To__c` field and returns the results in the following format:
```json
{
"Not Started": 1,
"Started": 0,
"Complete": 41
}
```

New Endpoints: `GET /enrollments/dropreasons` and `GET /tasks/{coachId}/stats`

---

.gitignore
docs/Scores - Salesforce Data API.postman_collection.json
docs/attendance-task-create.py
docs/data/attendance-task/query.txt
docs/data/attendance-task/results.csv
docs/sessions-no-results.py
scripts/exchange-update.py
src/main/mule/coach.xml
src/main/mule/main-api.xml
src/main/mule/scripts.xml
src/main/mule/tasks.xml
src/main/resources/api/salesforce-data-api.raml

1. **New header for error forwarding to understand what users experience issues: X-Firebase-UID**
---
2. **New endpoint GET `/coach/{coachId}/teamseasons/{teamSeasonId}/stats`**
---
3. **`startDate` and `endDate` query parameters for GET `/coach/{coachId}/teamseasons/{teamSeasonId}/sessions` as requested by Ammar**
---
4. **Python scripts to create tasks for sessions with no tasks**

Enhancements: Add 'X-Firebase-UID' Header, New Endpoints for Coach Team Seasons Stats, Date Filter for Sessions, and Task Creation Script

---

src/main/mule/coach.xml
src/main/mule/sessions.xml

All tests below are done locally using **production** credentials:
1. `GET /coach/{coachId}/teamseasons/{teamSeasonId}/sessions`
2. `GET /coach/{coachId}/allSessions`
3. `GET /sessions/{sessionId}`
4. `GET /coach/{coachId}/all`
5. `GET /sessions`

Add statistics per session using new fields `Count_Attendance_True__c` and `Count_Attendance_False__c`
